apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders-service
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders-service
    spec:
      containers:
      - image: southamerica-west1-docker.pkg.dev/shop-microservices-420215/image-registry/orders-service
        name: orders-service
        env:
        - name: PORT
          value: "3001"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: orders-secrets
              key: database_url
        resources: {}
status: {}
